project_id = "zdgczsslsobrqkpnqjhk"

[functions.generate-answer]
verify_jwt = false

[functions.embed-text]
verify_jwt = false

[functions.analyze-sentiment]
verify_jwt = false

[functions.analyze-anomalies]
verify_jwt = false
