// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zdgczsslsobrqkpnqjhk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpkZ2N6c3Nsc29icnFrcG5xamhrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3OTE1NzcsImV4cCI6MjA3MDM2NzU3N30.wIuwuRJCWbuhmTTMfLD614wrZ6skMUR96pWkt4gFp9A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});